services:
  - type: web
    name: chat-app-backend
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        value: your-mongodb-connection-string
